server:
  port: 8761


spring:
  application:
    name: eureka-server

#serviceUrl它指向与本地实例相同的主机
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
